/**
 * CQ v1.3 option labels → same tags as v1.4 (normalized keys).
 * Lets pre-migration attempts resolve tags without retaking the questionnaire.
 */
export const WELLNESS_LEGACY_OPTION_ALIASES: Record<string, Record<string, string | string[]>> = {
  wc_age_range: {
    "under 18": "age_under_18",
    "18-24": "age_18_24",
    "25-34": "age_25_34",
    "35-44": "age_35_44",
    "45-54": "age_45_54",
    "55+": "age_55_plus",
  },
  wc_work_lifestyle: {
    "desk-based / office work": "work_desk_based",
    "shift-based work": "work_shift_based",
    "physically demanding work": "work_physically_demanding",
    "travel-heavy work": "work_travel_heavy",
    "caregiving responsibilities": "lifestyle_caregiving",
    student: "lifestyle_student",
    "currently not working": "lifestyle_not_working",
  },
  wc_stress_level: {
    low: "stress_low",
    moderate: "stress_moderate",
    high: "stress_high",
  },
  wc_wellness_time: {
    "under 15 minutes": "time_under_15_min",
    "15-30 minutes": "time_15_30_min",
    "30-45 minutes": "time_30_45_min",
    "45+ minutes": "time_45_plus_min",
  },
  wc_fitness_level: {
    "beginner - i rarely exercise": "fitness_beginner",
    "restarting - i used to exercise but stopped": "fitness_restarting",
    "intermediate - i exercise occasionally": "fitness_intermediate",
    "consistent - i train regularly": "fitness_consistent",
    "advanced - i follow structured fitness programs": "fitness_advanced",
  },
  wc_daily_activity: {
    "mostly sedentary": "activity_sedentary",
    "lightly active": "activity_light",
    "moderately active": "activity_moderate",
    "very active": "activity_very_active",
  },
  wc_preferred_activities: {
    walking: "activity_pref_walking",
    running: "activity_pref_running",
    "strength / resistance training": "activity_pref_strength",
    "cardio machines": "activity_pref_cardio",
    "yoga / mind-body": "activity_pref_yoga",
    sports: "activity_pref_sports",
    dance: "activity_pref_dance",
    swimming: "activity_pref_swimming",
    cycling: "activity_pref_cycling",
    "home follow-along workouts": "activity_pref_home_followalong",
    "open to anything": "activity_pref_open",
  },
  wc_workout_environment: {
    "at home": "environment_home",
    gym: "environment_gym",
    outdoors: "environment_outdoors",
    "no preference": "environment_no_preference",
  },
  wc_time_of_day: {
    morning: "time_of_day_morning",
    daytime: "time_of_day_daytime",
    evening: "time_of_day_evening",
    "late night": "time_of_day_latenight",
    "no preference": "time_of_day_no_preference",
  },
  wc_sleep_quality: {
    "very poor": "sleep_quality_very_poor",
    poor: "sleep_quality_poor",
    average: "sleep_quality_average",
    good: "sleep_quality_good",
    excellent: "sleep_quality_excellent",
  },
  wc_sleep_hours: {
    "less than 5 hours": "sleep_under_5_hours",
    "5-6 hours": "sleep_5_6_hours",
    "6-7 hours": "sleep_6_7_hours",
    "7-8 hours": "sleep_7_8_hours",
    "more than 8 hours": "sleep_over_8_hours",
  },
  wc_caffeine_habit: {
    "none / rarely": "caffeine_none",
    "morning only": "caffeine_morning",
    "throughout the day": "caffeine_daytime",
    "evening or late day": "caffeine_evening",
  },
  wc_food_pattern: {
    vegetarian: "food_vegetarian",
    vegan: "food_vegan",
    eggetarian: "food_eggetarian",
    "non-vegetarian": "food_non_vegetarian",
    pescatarian: "food_pescatarian",
    "no specific preference": "food_no_preference",
  },
  wc_meal_control: {
    "i prepare most of my meals": "meal_control_self_prepared",
    "prepared by others": "meal_control_prepared_by_others",
    "frequent eating out": "meal_control_frequent_eating_out",
    mixed: "meal_control_mixed",
  },
  wc_wellness_goals: {
    "build muscle / get stronger": ["goal_muscle_gain", "goal_strength"],
    "fat loss": "goal_fat_loss",
    "better energy levels": "goal_energy",
    "less stress / mental calm": ["goal_stress_reduction", "goal_mental_calm"],
    "build a consistent routine": ["goal_consistency_discipline", "goal_sustainable_routines"],
    "improve sleep": "goal_sleep_improvement",
    "improve flexibility / mobility": "goal_flexibility_mobility",
    "improve overall health": "goal_overall_health",
    "better recovery": "goal_better_recovery",
    "sustainable routines": "goal_sustainable_routines",
    "return to fitness after a break": "goal_return_to_fitness",
  },
  wc_wellness_barriers: {
    "hard to get started": ["barrier_starting_difficulty", "barrier_low_activation_energy"],
    "lack of consistency": "barrier_lack_of_consistency",
    "work stress": "barrier_work_stress",
    "poor sleep": "barrier_poor_sleep",
    "low motivation": "barrier_low_motivation",
    "emotional eating / cravings": "barrier_emotional_eating_cravings",
    "gym anxiety": "barrier_gym_anxiety",
    "lack of knowledge": "barrier_lack_of_knowledge",
    "travel / schedule disruptions": "barrier_travel_schedule_disruption",
    "family responsibilities": "barrier_family_responsibilities",
    "injury or physical discomfort": "barrier_injury_discomfort",
    "overwhelm from complexity": "barrier_overwhelm_from_complexity",
  },
  wc_support_system: {
    "strong support": "support_strong",
    "some support": "support_some",
    neutral: "support_neutral",
    "unsupportive environment": "support_unsupportive",
  },
  wc_solo_vs_social: {
    "i prefer self-directed activities": "support_self_directed",
    "a balance of solo and social": "social_balanced",
    "i prefer social / group activities": "social_preference_high",
  },
  wc_health_flags: {
    "none of these apply": "exclude_none",
    "medical condition affecting activity or nutrition": "exclude_medical_condition",
    injury: "exclude_injury",
    "pregnancy or postpartum": "exclude_pregnancy_postpartum",
    "doctor-advised restriction": "exclude_doctor_advised_restriction",
    "prefer not to say": "exclude_prefer_not_to_say_health",
    "severe fatigue": "exclude_severe_fatigue",
    "persistent pain": "exclude_persistent_pain",
  },
};
