/**
 * CQ v1.3 / v1.4 option labels → tags (normalized keys).
 * Lets pre-migration attempts resolve tags without retaking the questionnaire.
 * v1.5 labels are covered by tag-mapping-rules.json directly.
 */
export const WELLNESS_LEGACY_OPTION_ALIASES: Record<string, Record<string, string | string[]>> = {
  wc_age_range: {
    "under 18": "age_under_18",
    "18-24": "age_18_24",
    "25-34": "age_25_34",
    "35-44": "age_35_44",
    "45-54": "age_45_54",
    "55+": "age_55_plus",
  },
  wc_work_lifestyle: {
    "desk-based / office work": "work_desk_based",
    "desk-based (office / remote / hybrid)": "work_desk_based",
    "desk-based": "work_desk_based",
    "shift-based work": "work_shift_based",
    "shift-based": "work_shift_based",
    "physically demanding work": "work_physically_demanding",
    "physically demanding": "work_physically_demanding",
    "travel-heavy work": "work_travel_heavy",
    "travel-heavy": "work_travel_heavy",
    "caregiving responsibilities": "lifestyle_caregiving",
    "homemaker or caregiver": "lifestyle_caregiving",
    student: "lifestyle_student",
    "currently not working": "lifestyle_not_working",
    "not currently working": "lifestyle_not_working",
    "not in active employment": "lifestyle_not_working",
  },
  wc_stress_level: {
    low: "stress_low",
    moderate: "stress_moderate",
    high: "stress_high",
  },
  wc_wellness_time: {
    "under 15 minutes": "time_under_15_min",
    "under 15 min": "time_under_15_min",
    "15-30 minutes": "time_15_30_min",
    "15-30 min": "time_15_30_min",
    "30-45 minutes": "time_30_45_min",
    "30-45 min": "time_30_45_min",
    "45+ minutes": "time_45_plus_min",
    "45+ min": "time_45_plus_min",
    "under 30 minutes": "time_under_30_min",
    "45-60 minutes": "time_45_60_min",
    "over 60 minutes": "time_over_60_min",
  },
  wc_fitness_level: {
    "beginner - i rarely exercise": "fitness_beginner",
    "new to exercise": "fitness_beginner",
    "restarting - i used to exercise but stopped": "fitness_restarting",
    "returning after a break": "fitness_restarting",
    "intermediate - i exercise occasionally": "fitness_intermediate",
    "exercise occasionally": "fitness_intermediate",
    "consistent - i train regularly": "fitness_consistent",
    "train regularly": "fitness_consistent",
    "advanced - i follow structured fitness programs": "fitness_advanced",
    "train with a structured program": "fitness_advanced",
  },
  wc_daily_activity: {
    "mostly sedentary": "activity_sedentary",
    sedentary: "activity_sedentary",
    "mostly sitting": "activity_sedentary",
    "lightly active": "activity_light",
    "moderately active": "activity_moderate",
    "very active": "activity_very_active",
  },
  wc_preferred_activities: {
    walking: "activity_pref_walking",
    running: "activity_pref_running",
    "running / jogging": "activity_pref_running",
    "strength / resistance training": "activity_pref_strength",
    "strength or weights": "activity_pref_strength",
    "strength or resistance training": "activity_cat_strength",
    "cardio machines": "activity_pref_cardio",
    "cardio / hiit": "activity_pref_cardio",
    "cardio or endurance": "activity_cat_cardio",
    "yoga / mind-body": "activity_pref_yoga",
    "yoga, pilates or stretching": "activity_pref_yoga",
    "mind-body or flexibility": "activity_cat_mindbody",
    sports: "activity_pref_sports",
    "sports or games": "activity_pref_sports",
    "learning a skill or sport": "activity_cat_skill_learning",
    dance: "activity_pref_dance",
    dancing: "activity_pref_dance",
    swimming: "activity_pref_swimming",
    cycling: "activity_pref_cycling",
    "home follow-along workouts": "activity_pref_home_followalong",
    "open to anything": "activity_pref_open",
  },
  wc_preferred_activity_details: {
    "running/jogging": "activity_pref_running",
    cycling: "activity_pref_cycling",
    swimming: "activity_pref_swimming",
    walking: "activity_pref_walking",
    hiit: "activity_pref_cardio",
    yoga: "activity_pref_yoga",
    pilates: "activity_pref_pilates",
    stretching: "activity_pref_stretching",
    dance: "activity_pref_dance",
    "tai chi": "activity_pref_taichi",
    "martial arts": "activity_pref_martial_arts",
    "a team sport": "activity_pref_sports",
    "a racquet sport": "activity_pref_racquet_sport",
    "dance form": "activity_pref_dance_form",
    "swimming (learning)": "activity_pref_swimming_learn",
  },
  wc_workout_environment: {
    "at home": "environment_home",
    gym: "environment_gym",
    "at a gym or training centre": "environment_gym",
    outdoors: "environment_outdoors",
    "no preference": "environment_no_preference",
  },
  wc_time_of_day: {
    morning: "time_of_day_morning",
    "early morning": "time_of_day_morning",
    daytime: "time_of_day_daytime",
    evening: "time_of_day_evening",
    "late night": "time_of_day_latenight",
    "no preference": "time_of_day_no_preference",
    "no fixed preference": "time_of_day_no_preference",
  },
  wc_sleep_quality: {
    "very poor": "sleep_quality_very_poor",
    poor: "sleep_quality_poor",
    average: "sleep_quality_average",
    good: "sleep_quality_good",
    excellent: "sleep_quality_excellent",
  },
  wc_sleep_hours: {
    "less than 5 hours": "sleep_under_5_hours",
    "under 5 hours": "sleep_under_5_hours",
    "5-6 hours": "sleep_5_6_hours",
    "6-7 hours": "sleep_6_7_hours",
    "7-8 hours": "sleep_7_8_hours",
    "more than 8 hours": "sleep_over_8_hours",
    "over 8 hours": "sleep_over_8_hours",
  },
  wc_caffeine_habit: {
    "none / rarely": "caffeine_none",
    none: "caffeine_none",
    "i don't have caffeine": "caffeine_none",
    "morning only": "caffeine_morning",
    "only in the morning": "caffeine_morning",
    "throughout the day": "caffeine_daytime",
    "through the day": "caffeine_daytime",
    "through the day, but not after 4 pm": "caffeine_daytime",
    "evening or late day": "caffeine_evening",
    "evening too": "caffeine_evening",
    "through the day, including evenings": "caffeine_evening",
  },
  wc_food_pattern: {
    vegetarian: "food_vegetarian",
    vegan: "food_vegan",
    eggetarian: "food_eggetarian",
    "non-vegetarian": "food_non_vegetarian",
    pescatarian: "food_pescatarian",
    "no specific preference": "food_no_preference",
    "no specific pattern": "food_no_preference",
  },
  wc_meal_control: {
    "i prepare most of my meals": "meal_control_self_prepared",
    "i cook most of my meals": "meal_control_self_prepared",
    "i decide and prepare most meals": "meal_control_self_prepared",
    "prepared by others": "meal_control_prepared_by_others",
    "someone else prepares most (home or cafeteria)": "meal_control_prepared_by_others",
    "someone else at home decides": "meal_control_prepared_by_others",
    "frequent eating out": "meal_control_frequent_eating_out",
    "i mostly eat out or order in": "meal_control_frequent_eating_out",
    mixed: "meal_control_mixed",
    "mixed / varies by day": "meal_control_mixed",
    "it varies": "meal_control_mixed",
  },
  wc_wellness_goals: {
    "build muscle / get stronger": ["goal_muscle_gain", "goal_strength"],
    "build strength or muscle": ["goal_muscle_gain", "goal_strength"],
    "fat loss": "goal_fat_loss",
    "fat loss / weight management": "goal_fat_loss",
    "lose weight or manage body fat": "goal_fat_loss",
    "better energy levels": "goal_energy",
    "more energy through the day": "goal_energy",
    "have more energy and feel better": "goal_energy",
    "less stress / mental calm": ["goal_stress_reduction", "goal_mental_calm"],
    "reduce stress and feel calmer": "goal_stress_reduction",
    "build a consistent routine": [
      "goal_consistency_discipline",
      "goal_consistency",
      "goal_sustainable_routines",
    ],
    "improve sleep": "goal_sleep_improvement",
    "better sleep": "goal_sleep_improvement",
    "sleep better and recover well": ["goal_sleep_recovery", "goal_sleep_improvement"],
    "improve flexibility / mobility": "goal_flexibility_mobility",
    "flexibility / mobility": "goal_flexibility_mobility",
    "improve overall health": "goal_overall_health",
    "overall health": "goal_overall_health",
    "better recovery": "goal_better_recovery",
    "sustainable routines": "goal_sustainable_routines",
    "return to fitness after a break": "goal_return_to_fitness",
    "get back into fitness after a break": "goal_return_to_fitness",
    "body confidence / appearance": "goal_body_confidence",
  },
  wc_wellness_barriers: {
    "hard to get started": ["barrier_starting_difficulty", "barrier_low_activation_energy"],
    "lack of consistency": "barrier_lack_of_consistency",
    "shortage of time": "barrier_lack_of_time",
    "lack of time": "barrier_lack_of_time",
    "work stress": "barrier_work_stress",
    "poor sleep": "barrier_poor_sleep",
    "low motivation": "barrier_low_motivation",
    "emotional eating / cravings": "barrier_emotional_eating_cravings",
    "emotional eating or cravings": "barrier_emotional_eating_cravings",
    "stress or emotional eating": "barrier_stress_emotional_eating",
    "gym anxiety": "barrier_gym_anxiety",
    "gym anxiety / self-consciousness": "barrier_gym_anxiety",
    "self-consciousness about exercising": "barrier_self_consciousness",
    "lack of knowledge": "barrier_lack_of_knowledge",
    "i don't know what to do": "barrier_lack_of_knowledge",
    "lack of knowledge or clarity": "barrier_lack_of_knowledge",
    "travel / schedule disruptions": "barrier_travel_schedule_disruption",
    "travel or schedule disruption": "barrier_travel_schedule_disruption",
    "unpredictable schedule or routine": "barrier_unpredictable_schedule",
    "family responsibilities": "barrier_family_responsibilities",
    "family / caregiving responsibilities": "barrier_family_responsibilities",
    "injury or physical discomfort": "barrier_injury_discomfort",
    "physical limitation or injury": "barrier_physical_limitation",
    "overwhelm from complexity": "barrier_overwhelm_from_complexity",
    "plans feel too complex / overwhelming": "barrier_overwhelm_from_complexity",
  },
  wc_support_system: {
    "strong support": "support_strong",
    "very supportive": "support_strong",
    "some support": "support_some",
    "somewhat supportive": "support_some",
    neutral: "support_neutral",
    "neutral or mixed": "support_neutral",
    "unsupportive environment": "support_unsupportive",
    unsupportive: "support_unsupportive",
    "not supportive": "support_unsupportive",
  },
  wc_solo_vs_social: {
    "i prefer self-directed activities": "support_self_directed",
    "mostly on my own": "support_self_directed",
    "a balance of solo and social": "social_balanced",
    "a mix": "social_balanced",
    "i prefer social / group activities": "social_preference_high",
    "mostly with others or a group": "social_preference_high",
  },
  wc_health_flags: {
    "none of these apply": "exclude_none",
    "no known restriction": "exclude_none",
    "no known issues": "exclude_none",
    "medical condition affecting activity or nutrition": "exclude_medical_condition",
    "medical condition": "exclude_medical_condition",
    "a medical condition": "exclude_medical_condition",
    injury: "exclude_injury",
    "an injury": "exclude_injury",
    "pregnancy or postpartum": "exclude_pregnancy_postpartum",
    "doctor-advised restriction": "exclude_doctor_advised_restriction",
    "a doctor-advised restriction": "exclude_doctor_advised_restriction",
    "prefer not to say": "exclude_prefer_not_to_say_health",
    "severe fatigue": "exclude_severe_fatigue",
    "severe fatigue (symptom)": "exclude_severe_fatigue",
    "ongoing fatigue": "exclude_severe_fatigue",
    "persistent pain": "exclude_persistent_pain",
    "persistent pain (symptom)": "exclude_persistent_pain",
  },
};
